scalar DateTime

type Address {
  streetAddress: string!
  city: string!
  state: string!
  postalCode: string!
  country: string!
}

type ContactInfo {
  phone: string
  email: string
  mailingAddress: Address
}

type Person {
  givenName: string!
  surName: string!
  contactInfo: ContactInfo!
}

type User {
  username: string!
  person: Person!
  role: string!
}

type Customer {
  id: string!
  person: Person!
}

enum ContactMedium {
  EMAIL
  PHONE
  CONVERSATION
  LETTER
}

union ContactIndividual = Customer | User

type Contact {
  id: string!
  medium: ContactMedium
  from: ContactIndividual
  to: ContactIndividual
  date: DateTime!
  subject: string!
  contents: string!
  survey: SurveyTemplate
}

type SurveyTemplate {
  id: string!
  questions: SurveyQuestion[]!
  author: User!
  name: string!
}

union CommentSubject = Comment | SurveyTemplate | Customer

type Comment {
  author: User!
  subject: CommentSubject!
  message: string!
  date: DateTime!
}

type Query {
  getCustomers(page: int = 0, firstName: string, lastName: string): Customer[]
}
