name: Build Schema
on: push
jobs:
    build:
        name: Build schema
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install
              run: npm i

            - name: Run build script
              run: npm run build

            - name: Update schema
              permissions:
                  id-token: write
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: ./schema.graphql
                  commit-msg: Build schema
                  github-token: ${{ secrets.GITHUB_TOKEN }}